pub mod backend;
pub mod config;
pub mod discovery;
pub mod error;
pub mod registry;
pub mod rf_backend;
pub mod sequencer;
pub mod services;
pub mod session;
pub mod system;
pub mod transport;
pub mod usb_transport;
pub use frgb_ipc as ipc_client;
pub mod aura_backend;
pub mod hwmon;
pub mod hwmon_backend;
pub mod lcd_backend;
pub mod openrgb_backend;
pub mod wired_ene_backend;

pub use aura_backend::AuraBackend;
pub use hwmon_backend::HwmonBackend;
pub use backend::{Backend, BackendId, DiscoveredDevice, LcdExt, LianLiRfExt};
pub use error::{CoreError, Result};
pub use lcd_backend::LcdBackend;
pub use openrgb_backend::OpenRgbBackend;
pub use registry::{Device, DeviceRegistry, DeviceSlot, DeviceState};
pub use rf_backend::LianLiRfBackend;
pub use system::System;
pub use transport::Transport;
pub use usb_transport::UsbTransport;
pub use wired_ene_backend::WiredEneBackend;
